spring:
  application:
    name: demo

  jpa:
    #show-sql: true # Debugging
    hibernate:
      #format_sql: true # Debugging
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

  datasource:
    url: jdbc:oracle:thin:@host.docker.internal:1521:ORCLCDB
    username: system
    password: topsecretpass
    driver:
        class-name: oracle.jdbc.OracleDriver

  flyway:
    baselineOnMigrate: true

  kafka:
    bootstrap-servers: host.docker.internal:29092

  redis:
    ttl: 5
    hostname: host.docker.internal

  task:
    thread-name-prefix: demo-
    execution:
      core-size: 2
      max-size: 2
      queue-capacity: 500

dgs:
  graphql:
    schema-locations: "classpath*:graphql/**/*.graphql*"

logging:
  level:
    org.flywaydb: debug
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    #org.springframework.jdbc.core.JdbcTemplate: DEBUG
    #org.springframework.jdbc.core.StatementCreatorUtils: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "health"

# Skip DGS controller(s) for Swagger API documentation
springdoc:
  packages-to-exclude: com.netflix.graphql.dgs.mvc
