apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
    - port: 9092
      name: plaintext-port
      targetPort: 9092
    - port: 29092
      name: plaintext-host-port
      targetPort: 29092
  selector:
    app: kafka
